export const ACTION_ADD_EXPRESSION = 'ADD_EXPRESSION';

export const ACTION_CLEAR_EXPRESSION = 'CLEAR_EXPRESSION';

export const ACTION_SAVED_NUMBER = 'SAVED_NUMBER';

export const ACTION_SET_THEME = 'SET_THEME';
