export const THEME_MODE = {
  'DARK': 'dark',
  'LIGHT': 'light',
  'COLORED': 'colored',
}

export const darkTheme = {
  mode: THEME_MODE.DARK,
  PRIMARY_BACKGROUND_COLOR: '#fff',
  PRIMARY_BACKGROUND_HEADER_COLOR: '#000',
  PRIMARY_TEXT_COLOR: '#000',
  PRIMARY_TEXT_HOVER_COLOR: '#fff',
  PRIMARY_TEXT_HEADER_COLOR: '#b0acac',
  SECONDARY_TEXT_COLOR: '#000',
}

export const lightTheme = {
  mode: THEME_MODE.LIGHT,
  PRIMARY_BACKGROUND_COLOR: '#fbd1d1',
  PRIMARY_BACKGROUND_HEADER_COLOR: '#505050',
  PRIMARY_TEXT_COLOR: '#505050',
  PRIMARY_TEXT_HOVER_COLOR: '#fff',
  PRIMARY_TEXT_HEADER_COLOR: '#999',
  SECONDARY_TEXT_COLOR: '#000',
}

export const coloredTheme = {
  mode: THEME_MODE.COLORED,
  PRIMARY_BACKGROUND_COLOR: '#fff',
  PRIMARY_BACKGROUND_HEADER_COLOR: 'red',
  PRIMARY_TEXT_COLOR: '#000',
  PRIMARY_TEXT_HOVER_COLOR: '#fff',
  PRIMARY_TEXT_HEADER_COLOR: '#000',
  SECONDARY_TEXT_COLOR: '#000',
}